#!/usr/bin/env python3
"""Generate N explicitly-written resource pairs (NO count / for_each).

Each pair is:
  - a random_pet that produces a distinct name, and
  - an aws_ssm_parameter that uses that name.

So the config has N hand-written resource *blocks* with distinct addresses
(p0..p{N-1}), rather than a single resource with N instances. The SSM
parameter depends on its random_pet, giving each pair a little depth.

Usage:
    python3 gen.py [N]      # default 50
"""
import os
import sys

n = int(sys.argv[1]) if len(sys.argv) > 1 else 50
here = os.path.dirname(os.path.abspath(__file__))

blocks = []
for i in range(n):
    blocks.append(f'''resource "random_pet" "p{i}" {{
  length = 3
}}

resource "aws_ssm_parameter" "p{i}" {{
  name  = "/tfperf/${{random_pet.p{i}.id}}"
  type  = "String"
  value = "v{i}"
}}''')

out = os.path.join(here, "resources.tf")
with open(out, "w") as f:
    f.write(f"# GENERATED by gen.py — {n} explicit resource pairs, no count/for_each.\n")
    f.write(f"# {n} random_pet (distinct names) + {n} aws_ssm_parameter = {2*n} resources.\n\n")
    f.write("\n\n".join(blocks))
    f.write("\n")
print(f"wrote {out}: {n} explicit random_pet + aws_ssm_parameter pairs ({2*n} resources total)")
