# GENERATED by gen.py — 50 explicit resource pairs, no count/for_each.
# 50 random_pet (distinct names) + 50 aws_ssm_parameter = 100 resources.

resource "random_pet" "p0" {
  length = 3
}

resource "aws_ssm_parameter" "p0" {
  name  = "/tfperf/${random_pet.p0.id}"
  type  = "String"
  value = "v0"
}

resource "random_pet" "p1" {
  length = 3
}

resource "aws_ssm_parameter" "p1" {
  name  = "/tfperf/${random_pet.p1.id}"
  type  = "String"
  value = "v1"
}

resource "random_pet" "p2" {
  length = 3
}

resource "aws_ssm_parameter" "p2" {
  name  = "/tfperf/${random_pet.p2.id}"
  type  = "String"
  value = "v2"
}

resource "random_pet" "p3" {
  length = 3
}

resource "aws_ssm_parameter" "p3" {
  name  = "/tfperf/${random_pet.p3.id}"
  type  = "String"
  value = "v3"
}

resource "random_pet" "p4" {
  length = 3
}

resource "aws_ssm_parameter" "p4" {
  name  = "/tfperf/${random_pet.p4.id}"
  type  = "String"
  value = "v4"
}

resource "random_pet" "p5" {
  length = 3
}

resource "aws_ssm_parameter" "p5" {
  name  = "/tfperf/${random_pet.p5.id}"
  type  = "String"
  value = "v5"
}

resource "random_pet" "p6" {
  length = 3
}

resource "aws_ssm_parameter" "p6" {
  name  = "/tfperf/${random_pet.p6.id}"
  type  = "String"
  value = "v6"
}

resource "random_pet" "p7" {
  length = 3
}

resource "aws_ssm_parameter" "p7" {
  name  = "/tfperf/${random_pet.p7.id}"
  type  = "String"
  value = "v7"
}

resource "random_pet" "p8" {
  length = 3
}

resource "aws_ssm_parameter" "p8" {
  name  = "/tfperf/${random_pet.p8.id}"
  type  = "String"
  value = "v8"
}

resource "random_pet" "p9" {
  length = 3
}

resource "aws_ssm_parameter" "p9" {
  name  = "/tfperf/${random_pet.p9.id}"
  type  = "String"
  value = "v9"
}

resource "random_pet" "p10" {
  length = 3
}

resource "aws_ssm_parameter" "p10" {
  name  = "/tfperf/${random_pet.p10.id}"
  type  = "String"
  value = "v10"
}

resource "random_pet" "p11" {
  length = 3
}

resource "aws_ssm_parameter" "p11" {
  name  = "/tfperf/${random_pet.p11.id}"
  type  = "String"
  value = "v11"
}

resource "random_pet" "p12" {
  length = 3
}

resource "aws_ssm_parameter" "p12" {
  name  = "/tfperf/${random_pet.p12.id}"
  type  = "String"
  value = "v12"
}

resource "random_pet" "p13" {
  length = 3
}

resource "aws_ssm_parameter" "p13" {
  name  = "/tfperf/${random_pet.p13.id}"
  type  = "String"
  value = "v13"
}

resource "random_pet" "p14" {
  length = 3
}

resource "aws_ssm_parameter" "p14" {
  name  = "/tfperf/${random_pet.p14.id}"
  type  = "String"
  value = "v14"
}

resource "random_pet" "p15" {
  length = 3
}

resource "aws_ssm_parameter" "p15" {
  name  = "/tfperf/${random_pet.p15.id}"
  type  = "String"
  value = "v15"
}

resource "random_pet" "p16" {
  length = 3
}

resource "aws_ssm_parameter" "p16" {
  name  = "/tfperf/${random_pet.p16.id}"
  type  = "String"
  value = "v16"
}

resource "random_pet" "p17" {
  length = 3
}

resource "aws_ssm_parameter" "p17" {
  name  = "/tfperf/${random_pet.p17.id}"
  type  = "String"
  value = "v17"
}

resource "random_pet" "p18" {
  length = 3
}

resource "aws_ssm_parameter" "p18" {
  name  = "/tfperf/${random_pet.p18.id}"
  type  = "String"
  value = "v18"
}

resource "random_pet" "p19" {
  length = 3
}

resource "aws_ssm_parameter" "p19" {
  name  = "/tfperf/${random_pet.p19.id}"
  type  = "String"
  value = "v19"
}

resource "random_pet" "p20" {
  length = 3
}

resource "aws_ssm_parameter" "p20" {
  name  = "/tfperf/${random_pet.p20.id}"
  type  = "String"
  value = "v20"
}

resource "random_pet" "p21" {
  length = 3
}

resource "aws_ssm_parameter" "p21" {
  name  = "/tfperf/${random_pet.p21.id}"
  type  = "String"
  value = "v21"
}

resource "random_pet" "p22" {
  length = 3
}

resource "aws_ssm_parameter" "p22" {
  name  = "/tfperf/${random_pet.p22.id}"
  type  = "String"
  value = "v22"
}

resource "random_pet" "p23" {
  length = 3
}

resource "aws_ssm_parameter" "p23" {
  name  = "/tfperf/${random_pet.p23.id}"
  type  = "String"
  value = "v23"
}

resource "random_pet" "p24" {
  length = 3
}

resource "aws_ssm_parameter" "p24" {
  name  = "/tfperf/${random_pet.p24.id}"
  type  = "String"
  value = "v24"
}

resource "random_pet" "p25" {
  length = 3
}

resource "aws_ssm_parameter" "p25" {
  name  = "/tfperf/${random_pet.p25.id}"
  type  = "String"
  value = "v25"
}

resource "random_pet" "p26" {
  length = 3
}

resource "aws_ssm_parameter" "p26" {
  name  = "/tfperf/${random_pet.p26.id}"
  type  = "String"
  value = "v26"
}

resource "random_pet" "p27" {
  length = 3
}

resource "aws_ssm_parameter" "p27" {
  name  = "/tfperf/${random_pet.p27.id}"
  type  = "String"
  value = "v27"
}

resource "random_pet" "p28" {
  length = 3
}

resource "aws_ssm_parameter" "p28" {
  name  = "/tfperf/${random_pet.p28.id}"
  type  = "String"
  value = "v28"
}

resource "random_pet" "p29" {
  length = 3
}

resource "aws_ssm_parameter" "p29" {
  name  = "/tfperf/${random_pet.p29.id}"
  type  = "String"
  value = "v29"
}

resource "random_pet" "p30" {
  length = 3
}

resource "aws_ssm_parameter" "p30" {
  name  = "/tfperf/${random_pet.p30.id}"
  type  = "String"
  value = "v30"
}

resource "random_pet" "p31" {
  length = 3
}

resource "aws_ssm_parameter" "p31" {
  name  = "/tfperf/${random_pet.p31.id}"
  type  = "String"
  value = "v31"
}

resource "random_pet" "p32" {
  length = 3
}

resource "aws_ssm_parameter" "p32" {
  name  = "/tfperf/${random_pet.p32.id}"
  type  = "String"
  value = "v32"
}

resource "random_pet" "p33" {
  length = 3
}

resource "aws_ssm_parameter" "p33" {
  name  = "/tfperf/${random_pet.p33.id}"
  type  = "String"
  value = "v33"
}

resource "random_pet" "p34" {
  length = 3
}

resource "aws_ssm_parameter" "p34" {
  name  = "/tfperf/${random_pet.p34.id}"
  type  = "String"
  value = "v34"
}

resource "random_pet" "p35" {
  length = 3
}

resource "aws_ssm_parameter" "p35" {
  name  = "/tfperf/${random_pet.p35.id}"
  type  = "String"
  value = "v35"
}

resource "random_pet" "p36" {
  length = 3
}

resource "aws_ssm_parameter" "p36" {
  name  = "/tfperf/${random_pet.p36.id}"
  type  = "String"
  value = "v36"
}

resource "random_pet" "p37" {
  length = 3
}

resource "aws_ssm_parameter" "p37" {
  name  = "/tfperf/${random_pet.p37.id}"
  type  = "String"
  value = "v37"
}

resource "random_pet" "p38" {
  length = 3
}

resource "aws_ssm_parameter" "p38" {
  name  = "/tfperf/${random_pet.p38.id}"
  type  = "String"
  value = "v38"
}

resource "random_pet" "p39" {
  length = 3
}

resource "aws_ssm_parameter" "p39" {
  name  = "/tfperf/${random_pet.p39.id}"
  type  = "String"
  value = "v39"
}

resource "random_pet" "p40" {
  length = 3
}

resource "aws_ssm_parameter" "p40" {
  name  = "/tfperf/${random_pet.p40.id}"
  type  = "String"
  value = "v40"
}

resource "random_pet" "p41" {
  length = 3
}

resource "aws_ssm_parameter" "p41" {
  name  = "/tfperf/${random_pet.p41.id}"
  type  = "String"
  value = "v41"
}

resource "random_pet" "p42" {
  length = 3
}

resource "aws_ssm_parameter" "p42" {
  name  = "/tfperf/${random_pet.p42.id}"
  type  = "String"
  value = "v42"
}

resource "random_pet" "p43" {
  length = 3
}

resource "aws_ssm_parameter" "p43" {
  name  = "/tfperf/${random_pet.p43.id}"
  type  = "String"
  value = "v43"
}

resource "random_pet" "p44" {
  length = 3
}

resource "aws_ssm_parameter" "p44" {
  name  = "/tfperf/${random_pet.p44.id}"
  type  = "String"
  value = "v44"
}

resource "random_pet" "p45" {
  length = 3
}

resource "aws_ssm_parameter" "p45" {
  name  = "/tfperf/${random_pet.p45.id}"
  type  = "String"
  value = "v45"
}

resource "random_pet" "p46" {
  length = 3
}

resource "aws_ssm_parameter" "p46" {
  name  = "/tfperf/${random_pet.p46.id}"
  type  = "String"
  value = "v46"
}

resource "random_pet" "p47" {
  length = 3
}

resource "aws_ssm_parameter" "p47" {
  name  = "/tfperf/${random_pet.p47.id}"
  type  = "String"
  value = "v47"
}

resource "random_pet" "p48" {
  length = 3
}

resource "aws_ssm_parameter" "p48" {
  name  = "/tfperf/${random_pet.p48.id}"
  type  = "String"
  value = "v48"
}

resource "random_pet" "p49" {
  length = 3
}

resource "aws_ssm_parameter" "p49" {
  name  = "/tfperf/${random_pet.p49.id}"
  type  = "String"
  value = "v49"
}
